apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-world
  namespace: secret-world
  labels:
    app: secret-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-world
  template:
    metadata:
      labels:
        app: secret-world
    spec:
      containers:
      - name: secret-world
        image: docker.io/eduhass/secret-world:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: secret-world
  namespace: secret-world
spec:
  selector:
    app: secret-world
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secret-world-ingress
  namespace: secret-world
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - secretworld.hasslab.tech
    secretName: secret-world-tls
  rules:
  - host: secretworld.hasslab.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secret-world
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secret-world-tls
  namespace: secret-world
spec:
  secretName: secret-world-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - secretworld.hasslab.tech  # Substitua pelo seu domínio real
  duration: 2160h # 90d
  renewBefore: 360h # 15d